=== ConnectionMaster/cortx-manager/experiments/validator_comparison/schema/sspl_schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "id": "http://json-schema.org/draft-03/schema#",
  "type": "object",
  "properties": {
    "username": {
      "type": "string",
      "required": true,
      "description": "User name."
    },
    "description": {
      "type": "string",
      "required": true,
      "description": "description."
    },
    "title": {
      "type": "string",
      "required": true,
      "description": "Title"
    },
    "expires": {
      "type": "integer",
      "required": true,
      "description": "expires in time seconds"
    },
    "signature": {
      "type": "string",
      "required": true,
      "description": "signature"
    },
    "time": {
      "type": "string",
      "required": true,
      "description": "Origination time of the alert"
    },
    "message": {
      "type": "object",
      "properties": {
        "sspl_ll_msg_header": {
          "type": "object",
          "properties": {
            "msg_version": {
              "type": "string",
              "required": true,
              "description": "signature"
            },
            "schema_version": {
              "type": "string",
              "required": true,
              "description": "Origination time of the alert"
            },
            "sspl_version": {
              "type": "string",
              "required": true,
              "description": "Origination time of the alert"
            }
          }
        },
        "sensor_response_type": {
          "type": "object",
          "properties": {
            "enclosure_psu_alert": {
              "type": "object",
              "properties": {

                "info": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "required": true,
                      "status": "status"
                    },
                    "dc12v": {
                      "type": "integer",
                      "required": true,
                      "description": "dc12v"
                    },
                    "dctemp": {
                      "type": "integer",
                      "required": true,
                      "description": "dctemp"
                    },
                    "vendor": {
                      "type": "string",
                      "required": true,
                      "description": "vendor"
                    },
                    "description": {
                      "type": "string",
                      "required": true,
                      "description": "description"
                    }
                  }
                },
                "alert_type": {
                  "type": "string",
                  "required": true,
                  "description": "Origination time of the alert"
                },
                "extended_info": {
                  "type": "object",
                  "properties": {
                    "position": {
                      "type": "string",
                      "required": true,
                      "status": "status"
                    },
                    "durable_id": {
                      "type": "string",
                      "required": true,
                      "description": "dc12v"
                    }
                  }
                },
                "resource_type": {
                  "type": "string",
                  "required": true,
                  "description": "resource type"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== ConnectionMaster/cortx-manager/test/alert_input.json
[
{
    "username": "sspl-ll",
    "description": "Seagate Storage Platform Library - Low Level - Sensor Response",
    "title": "SSPL-LL Sensor Response",
    "expires": 3600,
    "signature": "None",
    "time": "2019-07-25 11:24:39.303712",
    "message": {
        "sspl_ll_msg_header": {
            "msg_version": "1.0.0",
            "schema_version": "1.0.0",
            "sspl_version": "1.0.0"
        },
        "sensor_response_type": {
            "enclosure_psu_alert": {
                "info": {
                    "status": "Not Present",
                    "dc12v": 0,
                    "dctemp": 0,
                    "vendor": "",
                    "description": "",
                    "enclosure-id": 0,
                    "dc33v": 0,
                    "mfg-vendor-id": "",
                    "fru-shortname": "",
                    "location": "Enclosure 0 - Right",
                    "health-reason": "The power supply is not installed.",
                    "serial-number": "",
                    "health": "Fault",
                    "mfg-date": "N/A",
                    "part-number": "",
                    "model": "",
                    "health-recommendation": "- If the power supply is missing, insert a power supply of the correct type.  - If the power supply is present, confirm that it is fully inserted and locked in place.  - If the above steps do not resolve the issue, the power supply has probably failed and if the error persists, it should be replaced.",
                    "revision": "",
                    "dc5v": 0,
                    "dc12i": 0,
                    "dc5i": 0
                },
                "alert_type": "missing",
                "extended_info": {
                    "position": "Right",
                    "durable-id": "psu_0.1"
                },
                "resource_type": "fru"
            }
        }
    }
},
{
    "username": "sspl-ll",
    "description": "Seagate Storage Platform Library - Low Level - Sensor Response",
    "title": "SSPL-LL Sensor Response",
    "expires": 3600,
    "signature": "None",
    "time": "2019-07-25 02:08:00.771334",
    "message": {
        "sspl_ll_msg_header": {
            "msg_version": "1.0.0",
            "schema_version": "1.0.0",
            "sspl_version": "1.0.0"
        },
        "sensor_response_type": {
            "enclosure_fan_module_alert": {
                "info": {
                    "fan_module": {
                        "status": "OK",
                        "name": "Fan Module 4",
                        "enclosure-id": 0,
                        "fans": [
                            {
                                "status": "Up",
                                "name": "Fan 0",
                                "speed": 7440,
                                "durable-id": "fan_0.fm4.0",
                                "fw-revision": "",
                                "health-reason": "",
                                "serial-number": "N/A",
                                "health": "OK",
                                "location": "Enclosure 0, Fan Module 4",
                                "part-number": "N/A",
                                "position": "N/A",
                                "health-recommendation": "",
                                "hw-revision": "",
                                "locator-led": "Off"
                            },
                            {
                                "status": "Up",
                                "name": "Fan 1",
                                "speed": 7500,
                                "durable-id": "fan_0.fm4.1",
                                "fw-revision": "",
                                "health-reason": "",
                                "serial-number": "N/A",
                                "health": "OK",
                                "location": "Enclosure 0, Fan Module 4",
                                "part-number": "N/A",
                                "position": "N/A",
                                "health-recommendation": "",
                                "hw-revision": "",
                                "locator-led": "Off"
                            }
                        ],
                        "health-reason": "",
                        "health": "OK",
                        "location": "Enclosure 0 - Right",
                        "health-recommendation": ""
                    }
                },
                "alert_type": "fault_resolved",
                "extended_info": {
                    "fan_module": {
                        "position": "Indexed",
                        "durable-id": "fan_module_0.4"
                    }
                },
                "resource_type": "fru"
            }
        }
    }
}
]

=== ConnectionMaster/cortx-manager/test/test_data/alert_input.json
[
    {
        "username": "sspl-ll",
        "description": "Seagate Storage Platform Library - Low Level - Sensor Response",
        "title": "SSPL-LL Sensor Response",
        "expires": 3600,
        "signature": "None",
        "time": "2019-11-18 16:48:30.055424",
        "message": {
          "sspl_ll_msg_header": {
            "msg_version": "1.0.0",
            "schema_version": "1.0.0",
            "sspl_version": "1.0.0"
          },
          "sensor_response_type": {
            "info": {
              "event_time": "1574075909",
              "resource_id": "Fan Module 4",
              "site_id": 1,
              "node_id": 1,
              "cluster_id": 1,
              "rack_id": 1,
              "resource_type": "enclosure:fru:fan"
            },
            "alert_type": "missing",
            "severity": "critical",
            "specific_info": {
              "status": "Not Installed",
              "name": "Fan Module 4",
              "enclosure-id": 0,
              "durable-id": "fan_module_0.4",
              "fans": [],
              "health-reason": "The fan module is not installed.",
              "health": "Fault",
              "location": "Enclosure 0 - Right",
              "position": "Indexed",
              "health-recommendation": "Install the missing fan module."
            },
            "alert_id": "15740759091a4e14bca51d46908ac3e9102605d560",
            "host_id": "s3node-host-1"
          }
        }
      },
      {
        "username": "sspl-ll",
        "description": "Seagate Storage Platform Library - Low Level - Sensor Response",
        "title": "SSPL-LL Sensor Response",
        "expires": 3600,
        "signature": "None",
        "time": "2019-11-18 16:48:30.055000",
        "message": {
          "sspl_ll_msg_header": {
            "msg_version": "1.0.0",
            "schema_version": "1.0.0",
            "sspl_version": "1.0.0"
          },
          "sensor_response_type": {
            "info": {
              "event_time": "1574075909",
              "resource_id": "Fan Module 4",
              "site_id": 1,
              "node_id": 1,
              "cluster_id": 1,
              "rack_id": 1,
              "resource_type": "enclosure:fru:fan"
            },
            "alert_type": "missing",
            "severity": "critical",
            "specific_info": {
              "status": "Not Installed",
              "name": "Fan Module 4",
              "enclosure-id": 0,
              "durable-id": "fan_module_0.4",
              "fans": [],
              "health-reason": "The fan module is not installed.",
              "health": "Fault",
              "location": "Enclosure 0 - Right",
              "position": "Indexed",
              "health-recommendation": "Install the missing fan module."
            },
            "alert_id": "15740759091a4e14bca51d46908ac3e9102605d000",
            "host_id": "s3node-host-1"
          }
        }
      }
]

=== ConnectionMaster/cortx-manager/schema/node_actuator_request.json
{
 "username": "sspl-ll",
 "expires": 3600,
 "description": "Seagate Storage Platform Library - Low Level - Actuator Request",
 "title": "SSPL-LL Actuator Request",
 "signature": "None",
 "time": "",
 "message": {
   "sspl_ll_debug": {
     "debug_component": "sensor",
     "debug_enabled": true
   },
   "sspl_ll_msg_header": {
     "msg_version": "1.0.0",
     "uuid": "",
     "schema_version": "1.0.0",
     "sspl_version": "1.0.0"
   },
   "actuator_request_type": {
     "node_controller": {
       "node_request": "NDHW:",
       "resource": "*"
     }
   }
 }
}
